export const UPDATE_CONTACT_PAGE = "UPDATE_CONTACT_PAGE";
export const CLEAR_CONTACT_PAGE = "CLEAR_CONTACT_PAGE";

export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const END_AJAX_CALL = "END_AJAX_CALL";